### ISSUE TITLE
Update info missing

### ISSUE THREAD

**Issue by daKmoR** [open-wc/wild#12]
not sure what my current version is 😅 

but clicking on `Hey` gave me an empty update list like this

![Screenshot 2020-09-16 at 17 31 02](https://user-images.githubusercontent.com/24378/93359165-92a46a00-f842-11ea-8e1c-43afb62b4ba7.png)

**Comment by thepassle** [comment]
Could you check the version logged in the console and post the changelog.json from the network tab? 🤔

**Comment by daKmoR** [comment]
```
[Custom Elements in the wild] version: 1.0.2
```

changelog.json
```
{"Changelog":{"1.0.2":{"raw":"- Added quick-links so users can visit a site easily\n- Updated generic-components\n\n"},"1.0.1":{"raw":"- Fixed bug in keyboard control for dark mode toggle\n- Responsive styling fix\n\n"},"1.0.0":{"raw":"- Initial release\n\n\n"}}}
```

**Comment by thepassle** [comment]
Can you check if you have a `waiting` service worker in the `application` > `service worker` tab in devootls?

![image](https://user-images.githubusercontent.com/17054057/93361389-1bbca080-f845-11ea-9fef-3f1440728e89.png)

**Comment by thepassle** [comment]
The reason this is happening is because I cheated the update a little bit. I updated the `CHANGELOG.md` and `package.json` to `1.0.2` with the entry: `- Added quick-links so users can visit a site easily` in this commit https://github.com/open-wc/wild/commit/9572625f124d64017c3f113f3135b5e12e3a3dae

Then the next day I updated the version of generic components in commit https://github.com/open-wc/wild/commit/473358c3cd9d42a26acbd8c769c773a0ad0b1227, considering I hadnt told anybody about the quick-links update, I figured I'd just push this update along with the `1.0.2` version. However, it seems like you already found the `1.0.2` update _before_ I pushed the update of generic components to `1.0.2` as well.

For a user that _didnt_ update to `1.0.2`, the updates would show correctly and batched together. But since you already were on `1.0.2`, and since I didnt bump the version for the update of generic components, the semver diff returned an empty array, and displays nothing in the dialog.
