### ISSUE TITLE
offline state not showing

### ISSUE THREAD

**Issue by thepassle** [open-wc/wild#15]
In the code there's an offline state: https://github.com/open-wc/wild/blob/44325f8c7e27b81b0f42f446027935825bcb84b5/src/LocatorList.js#L432

in the right hand side of this ternary: https://github.com/open-wc/wild/blob/44325f8c7e27b81b0f42f446027935825bcb84b5/src/LocatorList.js#L408

But currently when a user is offline, we show "Something went wrong!", see:
![image](https://user-images.githubusercontent.com/17054057/93807220-9c670c80-fc4a-11ea-9bcb-56fc26b93753.png)

We should make sure the offline state works correctly 
Expected behavior: it doesnt show "Something went wrong!" when a user is offline, but it shows "Uh oh! Looks like you're not online ☹️"

How to test:
dev tools > network > offline

![image](https://user-images.githubusercontent.com/17054057/93807020-56aa4400-fc4a-11ea-9551-dfeebaaac23a.png)

**Comment by trystan2k** [comment]
Hi @thepassle,

Is this still happening ? I just tested with both the website and running locally with `npm run start` and both cases showed the correct message.

I tested with Chrome 85

![image](https://user-images.githubusercontent.com/447294/94857159-56bbf800-0431-11eb-8937-16e5738d3046.png)

**Comment by thepassle** [comment]
🤔 for me its not showing the correct state:
![image](https://user-images.githubusercontent.com/17054057/94857773-51ab7880-0432-11eb-819e-c78417c8ee7d.png)

**Comment by trystan2k** [comment]
Hi again.

I think I found the problem.

I just opened a PR #17 fixing it. 

The 'problem' was happening because when you (re)load and is offline, when the first fetch is done (in `connectedCallback`) it, obviously, fails and sets the `this.error` equals to `true` and later it checks if `!this.error` before checking if the navigator is online or not, so no matter if navigator is online or offline, if the first fetch fails, the 'Something went wrong!' message will stay there forever (as anywhere `this.error` is set back to false, unless you reload the page).

What I did was to change the verification order. Now it first checks if the navigator is online and if not, display the offline message no matter what this.error indicates (in this case we expect it to be `true` as the first fetch should have failed). 

Let me know what do you think about the solution. Hope it solves the problem (I did a couple of tests and seems to be working as expected now).

Thanks!
